spring:
  application:
    name: Article_Service
  profiles:
    active: native
    
 
    
    eureka:
  instance:
    nonSecurePort: ${server.port:8899}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8766}/eureka/
    
    
    spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver
    